FROM apache/airflow:2.10.5-python3.12 AS builder

RUN pip install --user --no-cache-dir \
	pandas \
	scikit-learn \
	joblib

FROM apache/airflow:2.10.5-python3.12

COPY --from=builder --chown=airflow:root /home/airflow/.local /home/airflow/.local